import { expect, test } from '@playwright/test';
test.afterEach(async () => { await new Promise((resolve) => setTimeout(resolve, 6500)); });
const secret = 'encrypted-e2e-secret-content';
async function create(page: import('@playwright/test').Page) { await page.goto('/'); const post = page.waitForRequest((r) => r.method() === 'POST' && r.url().includes('/api/v1/shares')); const response = page.waitForResponse((r) => r.request().method() === 'POST' && r.url().includes('/api/v1/shares')); await page.getByRole('radio', { name: 'Encrypted' }).click(); await page.getByRole('textbox', { name: 'Share text content' }).fill(secret); await page.getByRole('button', { name: 'Create share' }).click(); const body = JSON.parse((await post).postData()!); const payload = await (await response).json(); await expect(page.getByText('Share created')).toBeVisible(); const link = await page.getByLabel('Share link').inputValue(); return { id: payload.share.id as string, token: payload.owner_token as string, link, fragment: new URL(link).hash, body }; }
async function manage(page: import('@playwright/test').Page) { await page.getByRole('button', { name: 'Manage share' }).click(); await expect(page.getByLabel('Editor')).toBeVisible(); }

test('encrypted creation sends ciphertext only', async ({ page }) => { const x = await create(page); expect(x.body).toMatchObject({ payload_kind: 'TEXT', privacy_mode: 'ENCRYPTED', encrypted_text: { protocol: 'UPASTE_AES_GCM_V1' } }); expect(JSON.stringify(x.body)).not.toContain(secret); expect(x.link).toContain(`#up_e1_`); });
test('encrypted viewer decrypts only from fragment', async ({ page }) => { const x = await create(page); const get = page.waitForRequest((r) => r.method() === 'GET' && r.url().includes(`/shares/${x.id}`)); await page.getByRole('button', { name: 'Open share' }).click(); await expect(page.getByText(secret)).toBeVisible(); const request = await get; expect(request.url()).not.toContain(x.fragment.slice(1)); expect((await request.allHeaders()).referer || '').not.toContain(x.fragment.slice(1)); expect(page.url()).toContain(x.fragment); expect(page.getByRole('link', { name: 'Raw' })).toHaveCount(0); });
test('encrypted edit retains fragment and rotates nonce', async ({ page }) => { const x = await create(page); const oldNonce = x.body.encrypted_text.nonce; await manage(page); expect(page.url()).toContain(x.fragment); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Editor').fill('encrypted updated'); await page.getByRole('button', { name: 'Save changes' }).click(); const r = await req, body = JSON.parse(r.postData()!); expect(body).toHaveProperty('encrypted_text'); expect(body).not.toHaveProperty('text'); expect(JSON.stringify(body)).not.toContain('encrypted updated'); expect(body.encrypted_text.nonce).not.toBe(oldNonce); expect(r.url()).not.toContain(x.fragment.slice(1)); expect(page.url()).toContain(x.fragment); await page.getByRole('button', { name: 'Cancel' }).click(); await expect(page.getByText('encrypted updated')).toBeVisible(); });
test('encrypted expiration-only mutation does not send ciphertext', async ({ page }) => { const x = await create(page); await manage(page); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('1d'); await page.getByRole('button', { name: 'Save changes' }).click(); const body = JSON.parse((await req).postData()!); expect(body).toHaveProperty('expires_at'); expect(body).not.toHaveProperty('encrypted_text'); expect(body).not.toHaveProperty('text'); expect(page.url()).toContain(x.fragment); });
test('no-key owner management can mutate expiration only', async ({ page }) => { const x = await create(page); await page.goto(`/manage/${x.id}`); await page.getByLabel('Management token').fill(x.token); await page.getByRole('button', { name: 'Continue' }).click(); await expect(page.getByText(/Content editing is unavailable/)).toBeVisible(); await expect(page.getByLabel('Editor')).toHaveCount(0); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('1d'); await page.getByRole('button', { name: 'Update expiration' }).click(); const body = JSON.parse((await req).postData()!); expect(Object.keys(body)).toEqual(['expires_at']); });
test('wrong key retains owner expiry and delete authority', async ({ page }) => { const x = await create(page); await page.goto(`/manage/${x.id}#bad`); await page.getByLabel('Management token').fill(x.token); await page.getByRole('button', { name: 'Continue' }).click(); await expect(page.getByText(/Unable to decrypt this share/)).toBeVisible(); await expect(page.getByLabel('Editor')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Delete share' })).toBeVisible(); });
test('dirty encrypted delete clears fragment without refetch', async ({ page, request }) => { const x = await create(page); let gets = 0; page.on('request', (r) => { if (r.method() === 'GET' && r.url().includes(`/shares/${x.id}`)) gets++; }); await manage(page); const before = gets; await page.getByLabel('Editor').fill('dirty'); await page.getByRole('button', { name: 'Delete share' }).click(); await page.getByRole('button', { name: 'Delete permanently' }).click(); await expect(page.getByText('Share deleted')).toBeVisible(); await page.waitForTimeout(100); expect(page.url()).not.toContain('#up_e1_'); expect(gets).toBe(before); expect((await request.get(`http://127.0.0.1:4180/api/v1/shares/${x.id}`)).status()).toBe(404); });
