import { expect, test, type Page } from '@playwright/test';
test.afterEach(async () => { await new Promise((resolve) => setTimeout(resolve, 6500)); });
const secret = 'encrypted-e2e-secret-content';
async function surfaces(page: Page) { return page.evaluate(async () => ({ pathname: location.pathname, search: location.search, hash: location.hash, state: JSON.stringify(history.state), local: JSON.stringify(localStorage), session: JSON.stringify(sessionStorage), cookie: document.cookie, indexedDB: JSON.stringify(indexedDB.databases ? await indexedDB.databases() : []), caches: JSON.stringify('caches' in window ? await caches.keys() : []) })); }
async function create(page: Page) { await page.goto('/'); await page.getByRole('button', { name: 'EN' }).click(); const post = page.waitForRequest((r) => r.method() === 'POST' && r.url().includes('/api/v1/shares')); const response = page.waitForResponse((r) => r.request().method() === 'POST' && r.url().includes('/api/v1/shares')); await page.getByRole('radio', { name: 'Encrypted' }).click(); await page.getByLabel('Content', { exact: true }).fill(secret); await page.getByRole('button', { name: 'Create share' }).click(); const body = JSON.parse((await post).postData()!), payload = await (await response).json(); await expect(page.getByText('Share created')).toBeVisible(); const link = await page.getByLabel('Share link').inputValue(); return { id: payload.share.id as string, token: payload.owner_token as string, link, fragment: new URL(link).hash, body }; }
async function manage(page: Page) { await page.getByRole('button', { name: 'Manage share' }).click(); await expect(page.getByLabel('Editor')).toBeVisible(); }
function absent(s: unknown, ...values: string[]) { for (const v of values) expect(JSON.stringify(s)).not.toContain(v); }

test('encrypted creation sends ciphertext only', async ({ page }) => { const x = await create(page), key = x.fragment.slice(7), serialized = JSON.stringify(x.body); expect(x.body).toMatchObject({ payload_kind: 'TEXT', privacy_mode: 'ENCRYPTED', encrypted_text: { protocol: 'UPASTE_AES_GCM_V1' } }); expect(x.body.encrypted_text.nonce).not.toBe(''); expect(x.body.encrypted_text.ciphertext).not.toBe(''); absent(serialized, secret, key, x.fragment, x.token); expect(x.body).not.toHaveProperty('owner_token'); expect(x.body).not.toHaveProperty('text'); });
test('encrypted viewer decrypts only from fragment', async ({ page }) => { const x = await create(page), key = x.fragment.slice(7); const get = page.waitForRequest((r) => r.method() === 'GET' && r.url().includes(`/shares/${x.id}`)); await page.getByRole('button', { name: 'Open share' }).click(); await expect(page.getByText(secret)).toBeVisible(); const r = await get, s = await surfaces(page); absent(r.url(), key, x.fragment, x.token); absent((await r.allHeaders()).referer || '', key, x.token); expect(s).toMatchObject({ pathname: `/s/${x.id}`, search: '', hash: x.fragment }); absent({ ...s, hash: '' }, key, x.token); expect(page.getByRole('link', { name: 'Raw' })).toHaveCount(0); });
test('encrypted edit retains fragment and rotates nonce', async ({ page }) => { const x = await create(page), key = x.fragment.slice(7), old = x.body.encrypted_text.nonce; await manage(page); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Editor').fill('encrypted updated'); await page.getByRole('button', { name: 'Save changes' }).click(); const r = await req, body = JSON.parse(r.postData()!); expect(body).toHaveProperty('encrypted_text'); expect(body).not.toHaveProperty('text'); expect(body.encrypted_text.nonce).not.toBe(old); absent(body, secret, 'encrypted updated', key, x.fragment, x.token); absent(r.url(), key, x.token); expect((await r.allHeaders()).authorization).toBeTruthy(); expect((await surfaces(page)).hash).toBe(x.fragment); absent({ ...(await surfaces(page)), hash: '' }, key, x.token); await page.getByRole('button', { name: 'Cancel' }).click(); await expect(page.getByText('encrypted updated')).toBeVisible(); });
test('encrypted expiration-only mutation does not send ciphertext', async ({ page }) => { const x = await create(page), key = x.fragment.slice(7); await manage(page); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('1d'); await page.getByRole('button', { name: 'Save changes' }).click(); const r = await req, body = JSON.parse(r.postData()!); expect(body).toHaveProperty('expires_at'); expect(body).not.toHaveProperty('encrypted_text'); expect(body).not.toHaveProperty('text'); absent(body, secret, key, x.fragment, x.token); absent(r.url(), key, x.token); expect((await r.allHeaders()).authorization).toBeTruthy(); expect((await surfaces(page)).hash).toBe(x.fragment); });
test('no-key owner management can mutate expiration only', async ({ page }) => { const x = await create(page); await page.goto(`/manage/${x.id}`); await page.getByLabel('Management token').fill(x.token); await page.getByRole('button', { name: 'Continue' }).click(); await expect(page.getByText(/Content editing is unavailable/)).toBeVisible(); await expect(page.getByLabel('Editor')).toHaveCount(0); await expect(page.getByLabel('Expiration', { exact: true })).toBeEnabled(); await expect(page.getByRole('button', { name: 'Delete share' })).toBeVisible(); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('1d'); await page.getByRole('button', { name: 'Update expiration' }).click(); const body = JSON.parse((await req).postData()!); expect(Object.keys(body)).toEqual(['expires_at']); expect((await surfaces(page)).hash).toBe(''); });
test('wrong key retains owner expiry and delete authority', async ({ page }) => { const x = await create(page); await page.goto(`/manage/${x.id}#bad`); await page.getByLabel('Management token').fill(x.token); await page.getByRole('button', { name: 'Continue' }).click(); await expect(page.getByText(/Unable to decrypt this share/)).toBeVisible(); await expect(page.getByLabel('Editor')).toHaveCount(0); await expect(page.getByLabel('Expiration', { exact: true })).toBeEnabled(); await expect(page.getByRole('button', { name: 'Delete share' })).toBeVisible(); const req = page.waitForRequest((r) => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('1d'); await page.getByRole('button', { name: 'Update expiration' }).click(); const r = await req, body = JSON.parse(r.postData()!); expect(body).toHaveProperty('expires_at'); expect(body).not.toHaveProperty('text'); expect(body).not.toHaveProperty('encrypted_text'); absent(body, x.token, 'bad'); absent(r.url(), 'bad'); });
test('dirty encrypted delete clears fragment without refetch', async ({ page, request }) => { const x = await create(page), key = x.fragment.slice(7); let gets = 0; page.on('request', (r) => { if (r.method() === 'GET' && r.url().includes(`/shares/${x.id}`)) gets++; }); await manage(page); const before = gets; await page.getByLabel('Editor').fill('dirty'); await page.getByRole('button', { name: 'Delete share' }).click(); await page.getByRole('button', { name: 'Delete permanently' }).click(); await expect(page.getByText('Share deleted')).toBeVisible(); await expect(page.getByText(/Unsaved changes/)).toHaveCount(0); await page.waitForTimeout(100); const s = await surfaces(page); expect(s.pathname).toBe(`/manage/${x.id}`); expect(s.hash).toBe(''); expect(gets).toBe(before); absent(s, key, x.token); expect((await request.get(`http://127.0.0.1:4180/api/v1/shares/${x.id}`)).status()).toBe(404); });
