import { expect, test, type Page } from '@playwright/test';
const bytes = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 1, 2, 3, 4]); const name = 'file-e2e-fixture.png';
test.afterEach(async () => { await new Promise(r => setTimeout(r, 6500)); });
async function create(page: Page) { await page.goto('/'); await page.getByRole('tab', { name: 'File' }).click(); const post = page.waitForRequest(r => r.method() === 'POST' && r.url().includes('/api/v1/shares')); const res = page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('/api/v1/shares')); await page.locator('input[type=file]').setInputFiles({ name, mimeType: 'text/html', buffer: bytes }); await page.getByRole('button', { name: 'Create share' }).click(); const r = await res, data = await r.json(); await expect(page.getByRole('heading', { name: 'Share created' })).toBeVisible(); return { request: await post, response: r, data, id: data.share.id as string, token: data.owner_token as string, url: data.share.file.download_url as string }; }
async function manage(page: Page) { await page.getByRole('button', { name: 'Manage share' }).click(); }

test('real multipart creation uses server-sniffed metadata', async ({ page }) => { const x = await create(page), h = await x.request.allHeaders(); expect(h['content-type']).toMatch(/^multipart\/form-data; boundary=/); expect(x.response.status()).toBe(201); expect(x.data.share).toMatchObject({ payload_kind: 'FILE', privacy_mode: 'STANDARD', file: { filename: name, size: bytes.length, media_type: 'image/png' } }); expect(x.data.share.file.sha256).toMatch(/^[a-f0-9]{64}$/); expect(x.data.share.file.media_type).not.toBe('text/html'); expect(x.url).toBe(`http://127.0.0.1:4181/f/${x.id}`); });
test('viewer is metadata-only and does not auto-fetch bytes', async ({ page }) => { const x = await create(page); let hits = 0; page.on('request', r => { if (r.url() === x.url) hits++; }); await page.getByRole('button', { name: 'Open share' }).click(); await expect(page.getByText(name)).toBeVisible(); const link = page.getByRole('link', { name: 'Download file' }); await expect(link).toHaveAttribute('href', x.url); expect(hits).toBe(0); expect(await page.locator(`iframe[src="${x.url}"],img[src="${x.url}"],video[src="${x.url}"],audio[src="${x.url}"],object[data="${x.url}"],embed[src="${x.url}"]`).count()).toBe(0); });
test('file origin is exact-byte attachment with security headers', async ({ page, request }) => { const x = await create(page), r = await request.get(x.url), h = r.headers(); expect(r.status()).toBe(200); expect(Buffer.from(await r.body())).toEqual(bytes); expect(h['content-type']).toContain('image/png'); expect(h['content-disposition']).toContain('attachment'); expect(h['etag']).toMatch(/^"[a-f0-9]{64}"$/); for (const [k,v] of Object.entries({'x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY'})) expect(h[k]).toBe(v); expect(h['cache-control']).toContain('no-store'); expect(h['content-security-policy']).toContain('sandbox'); expect(h['access-control-allow-origin']).not.toBe('*'); });
test('HEAD and Range delivery behavior', async ({ page, request }) => { const x = await create(page), head = await request.head(x.url), range = await request.get(x.url, { headers: { Range: 'bytes=0-3' } }); expect(head.status()).toBe(200); expect(await head.body()).toHaveLength(0); expect(head.headers()['content-disposition']).toContain('attachment'); expect(range.status()).toBe(206); expect(Buffer.from(await range.body())).toEqual(bytes.subarray(0,4)); expect(range.headers()['content-range']).toMatch(/^bytes 0-3\//); });
test('management is expiry/delete-only and exact expiration mutations', async ({ page }) => { const x = await create(page); await manage(page); await expect(page.getByText(name)).toBeVisible(); await expect(page.getByLabel('Expiration', { exact: true })).toBeVisible(); await expect(page.getByLabel('Editor')).toHaveCount(0); await expect(page.locator('input[type=file]')).toHaveCount(0); const p = page.waitForRequest(r => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('1d'); await page.getByRole('button', { name: 'Update expiration' }).click(); const r = await p, body = JSON.parse(r.postData()!); expect(Object.keys(body)).toEqual(['expires_at']); expect((await r.allHeaders()).authorization).toBeTruthy(); expect(r.url()).not.toContain(x.token); const never = page.waitForRequest(r => r.method() === 'PATCH'); await page.getByLabel('Expiration', { exact: true }).selectOption('never'); await page.getByRole('button', { name: 'Update expiration' }).click(); expect(JSON.parse((await never).postData()!)).toEqual({ expires_at: null }); });
test('delete removes API metadata and file object', async ({ page, request }) => { const x = await create(page); await manage(page); await page.getByRole('button', { name: 'Delete share' }).click(); await page.getByRole('button', { name: 'Cancel' }).last().click(); await expect(page.getByRole('button', { name: 'Delete share' })).toBeVisible(); await page.getByRole('button', { name: 'Delete share' }).click(); await page.getByRole('button', { name: 'Delete permanently' }).click(); await expect(page.getByText('Share deleted')).toBeVisible(); expect((await request.get(`http://127.0.0.1:4180/api/v1/shares/${x.id}`)).status()).toBe(404); const get = await request.get(x.url), head = await request.head(x.url); expect(get.status()).toBe(404); expect(head.status()).toBe(404); expect(get.headers()['x-content-type-options']).toBe('nosniff'); expect(get.headers()['cache-control']).toContain('no-store'); });
