import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

const unicode = '中文，emoji 👩🏽‍💻 e\u0301 — العربية\n';
const longName = 'file-' + 'a'.repeat(170) + ' 中文 report.png';
const source = 'const url = "https://example.com/' + 'path'.repeat(100) + '";\n\treturn url;\n';
const markdown = '# Notes\n\n' + unicode + '\n- first\n- second\n\n1. one\n2. two\n\n> A quotation\n\n`inline` [link](https://example.com)\n\n```js\n' + source + '```\n\n| A | B |\n| - | - |\n| one | two |\n\n' + 'longword'.repeat(60);
const sizes = [[360, 800], [390, 844], [768, 1024], [1024, 768], [1440, 900]];

for (const [width, height] of sizes) for (const theme of ['light', 'dark']) {
  test(`${width} ${theme}: responsive create, viewers, management and dialogs`, async ({ page }) => {
    test.setTimeout(120_000);
    await page.setViewportSize({ width, height });
    await page.emulateMedia({ reducedMotion: 'reduce' });
    const check = async (state: string) => {
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
      await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
      if (process.env.UPASTE_QA_SCREENSHOTS) {
        await mkdir('/tmp/upaste-visual-qa', { recursive: true });
        await page.screenshot({ path: `/tmp/upaste-visual-qa/${width}-${theme}-${state}.png`, fullPage: true });
      }
    };
    const create = async (format: string, encrypted = false) => {
      await page.goto('/');
      await page.getByRole('button', { name: 'EN' }).click();
      await page.getByLabel('Format').selectOption(format === 'Plain text' ? 'PLAIN' : format === 'Source' ? 'SOURCE' : 'MARKDOWN');
      if (encrypted) await page.getByRole('radio', { name: 'Encrypted', exact: true }).click();
      await page.getByLabel('Content', { exact: true }).fill(format === 'Markdown' ? markdown : format === 'Source' ? source : unicode + 'token'.repeat(100));
      await check(encrypted ? 'encrypted-create' : `create-${format}`);
      const response = page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('/api/v1/shares'));
      await page.getByRole('button', { name: 'Create share', exact: true }).click();
      expect((await response).status()).toBe(201);
      const data = await (await response).json();
      await expect(page.getByLabel('Share link')).toBeVisible();
      // Never screenshot encrypted success: its key-bearing link is visible.
      if (!encrypted) await check('success-' + format);
      return data;
    };
    await page.goto('/');
    await expect(page.getByRole('heading', { name: '新建分享' })).toBeVisible();
    await page.getByLabel('外观').selectOption(theme);
    if (process.env.UPASTE_QA_SCREENSHOTS) {
      await mkdir('/tmp/upaste-visual-qa', { recursive: true });
      await page.screenshot({ path: `/tmp/upaste-visual-qa/${width}-${theme}-create-zh.png`, fullPage: true });
    }
    await page.getByRole('button', { name: 'EN' }).click();
    await page.getByLabel('Theme').focus();
    await expect(page.getByLabel('Theme')).toBeFocused();
    await check('create');
    await page.getByLabel('Content', { exact: true }).focus();
    await page.keyboard.press('Tab');
    await expect(page.getByLabel('Content', { exact: true })).not.toBeFocused();
    await page.getByLabel('Content', { exact: true }).fill('x'.repeat(1_048_570));
    await page.getByLabel('Content', { exact: true }).focus();
    expect(await page.getByLabel('Content', { exact: true }).evaluate(e => getComputedStyle(e).outlineStyle)).not.toBe('none');
    await check('near-limit');
    await page.getByLabel('Content', { exact: true }).fill('x'.repeat(1_048_577));
    await expect(page.getByRole('button', { name: 'Create share', exact: true })).toBeDisabled();
    await check('over-limit');
    await page.getByLabel('Content', { exact: true }).fill('');
    await create('Plain text');
    await page.getByRole('button', { name: 'Manage share', exact: true }).click();
    await expect(page.getByLabel('Editor')).toBeVisible();
    await check('manage');
    await page.getByLabel('Editor').focus();
    expect(await page.getByLabel('Editor').evaluate(e => getComputedStyle(e).outlineStyle)).not.toBe('none');
    await page.getByLabel('Editor').fill(unicode + 'dirty');
    await check('dirty');
    await page.getByRole('link', { name: 'uPaste Home' }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await check('unsaved');
    await page.getByRole('button', { name: 'Keep editing' }).click();
    await page.goBack();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('button', { name: 'Keep editing' }).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    await page.getByLabel('Editor').focus();
    await page.getByLabel('Editor').press('Control+Enter');
    await expect(page.getByText('Changes saved')).toBeVisible();
    await page.getByLabel('Expiration', { exact: true }).selectOption('custom');
    await check('custom-invalid');
    await page.getByLabel('Expiration', { exact: true }).selectOption('1d');
    await page.getByRole('button', { name: 'Save changes' }).click();
    await expect(page.getByText('Changes saved')).toBeVisible();
    await page.getByRole('button', { name: 'Delete share' }).click();
    const dialog = page.getByRole('dialog');
    await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused();
    const box = await dialog.boundingBox();
    expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.y).toBeGreaterThanOrEqual(0);
    expect(box!.y + box!.height).toBeLessThanOrEqual(height);
    await check('delete');
    await page.setViewportSize({ width, height: 240 });
    const shortBox = await dialog.boundingBox();
    expect(shortBox!.y).toBeGreaterThanOrEqual(0);
    expect(shortBox!.y + shortBox!.height).toBeLessThanOrEqual(240);
    await dialog.getByRole('button', { name: 'Delete permanently' }).focus();
    await page.keyboard.press('Tab');
    await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused();
    await page.setViewportSize({ width, height });
    await page.keyboard.press('Escape');
    await expect(page.getByRole('button', { name: 'Delete share' })).toBeFocused();
    expect(await page.evaluate(() => document.getElementById('root')?.inert)).toBe(false);
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(page.locator('.plain-text-content')).toBeVisible();
    await expect(page.locator('.plain-text-content')).toHaveText(unicode + 'dirty');
    await check('plain');
    await page.waitForTimeout(6500);
    await create('Source');
    await page.getByRole('button', { name: 'Open share' }).click();
    await expect(page.locator('.source-code-content')).toBeVisible();
    await check('source');
    expect(await page.locator('.source-code-content').evaluate(e => e.scrollWidth > e.clientWidth)).toBe(true);
    await page.waitForTimeout(6500);
    await create('Markdown');
    await page.getByRole('button', { name: 'Open share' }).click();
    await expect(page.locator('.markdown-body')).toBeVisible();
    await check('markdown');
    await page.getByRole('button', { name: 'Source', exact: true }).click();
    await expect(page.locator('.markdown-source-content')).toBeVisible();
    await check('markdown-source');
    await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    expect(await page.evaluate(() => scrollY)).toBeGreaterThan(0);
    await page.waitForTimeout(6500);
    const encrypted = await create('Plain text', true);
    await page.getByRole('button', { name: 'Manage share', exact: true }).click();
    await expect(page.getByLabel('Editor')).toBeVisible();
    await check('encrypted-manage');
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(page.locator('.plain-text-content')).toBeVisible();
    await check('encrypted-viewer');
    for (const hash of ['', '#bad']) {
      await page.goto(`/s/${encrypted.share.id}${hash}`);
      await expect(page.locator('.error-state-card')).toBeVisible();
      await check(hash ? 'wrong-key' : 'missing-key');
      await page.goto(`/manage/${encrypted.share.id}${hash}`);
      await expect(page.getByLabel('Management token')).toBeVisible();
      await check('token-gate');
      expect(await page.locator('.manage-card').evaluate(e => getComputedStyle(e).color)).toBe(theme === 'dark' ? 'rgb(241, 245, 249)' : 'rgb(15, 23, 42)');
      await page.getByLabel('Management token').fill(encrypted.owner_token);
      await page.getByRole('button', { name: 'Continue', exact: true }).click();
      await expect(page.getByRole('button', { name: 'Delete share' })).toBeVisible();
      await check(hash ? 'manage-wrong-key' : 'manage-no-key');
    }
    await page.waitForTimeout(6500);
    await page.goto('/');
    await page.getByRole('button', { name: 'EN' }).click();
    await page.getByRole('tab', { name: 'File', exact: true }).click();
    await check('file-empty');
    await page.locator('input[type=file]').setInputFiles({ name: longName, mimeType: 'image/png', buffer: Buffer.from([137,80,78,71,13,10,26,10,1,2]) });
    await check('file-selected');
    const uploaded = page.waitForResponse(r => r.request().method() === 'POST');
    await page.getByRole('button', { name: 'Create share', exact: true }).click();
    expect((await uploaded).status()).toBe(201);
    await expect(page.getByLabel('Share link')).toBeVisible();
    await check('file-success');
    await page.getByRole('button', { name: 'Manage share', exact: true }).click();
    await expect(page.getByText(longName, { exact: true })).toBeVisible();
    await check('file-manage');
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(page.getByRole('link', { name: 'Download file' })).toBeVisible();
    await check('file-viewer');
    await page.waitForTimeout(6500);
    await page.goto('/');
    await page.getByRole('button', { name: 'EN' }).click();
    await page.getByRole('tab', { name: 'File', exact: true }).click();
    await page.locator('input[type=file]').setInputFiles({ name: 'small.txt', mimeType: 'text/plain', buffer: Buffer.from('small file') });
    await page.getByRole('button', { name: 'Create share', exact: true }).click();
    await expect(page.getByLabel('Share link')).toBeVisible();
    await page.getByRole('button', { name: 'Open share' }).click();
    await expect(page.getByRole('link', { name: 'Download file' })).toBeVisible();
    await check('file-normal');
    await page.goto('/s/not-a-share');
    await expect(page.locator('.error-state-card')).toBeVisible();
    await check('404');
    await page.waitForTimeout(6500);
  });
}
