//go:build production

package webapp

import (
	"embed"
	"fmt"
	"io/fs"
)

// The dist directory is generated by scripts/build-production-binary.sh and is
// ignored by Git. A production build must stage the Vite output there before
// compiling with -tags production.
//
//go:embed all:dist
var embedded embed.FS

// NewEmbedded returns a handler backed by the production bundle.
func NewEmbedded() (*Handler, error) {
	assets, err := fs.Sub(embedded, "dist")
	if err != nil {
		return nil, fmt.Errorf("open embedded frontend bundle: %w", err)
	}
	return New(assets)
}
